jadwal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.jadwal),
    path('<int:pk>/', views.delete, name = 'hapus'),
]

naufal_profile/urls.py
from django.urls import path,include
from . import views

app_name = 'naufal_profile'

urlpatterns = [
    path('', views.index, name='index'),
    path('porto', views.porto, name='porto'),
    path('jadwal', include('jadwal.urls'), name='jadwal'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('naufal_profile.urls')),
    path('jadwal/', include('jadwal.urls'))
]

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nama_kegiatan = models.CharField(blank=False, max_length= 100)
    hari_kegiatan = models.CharField(blank=False, max_length= 100)
    tempat_kegiatan = models.CharField(blank=False, max_length= 100)
    kategori_kegiatan = models.CharField(blank=False, max_length= 100)
    waktu_kegiatan = models.DateTimeField(blank=False)

naufal_profile/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms

class formulir(forms.Form):
    nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Kegiatan',
        'type' : 'text',
        'required' : True
    }))
    waktu_kegiatan = forms.CharField(widget=forms.DateTimeInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Tanggal dan Waktu',
        'type' : 'datetime-local',
        'required' : True
    }))
    tempat_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Tempat Kegiatan',
        'type' : 'text',
        'required' : True
    }))
    kategori_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Kategori Kegiatan',
        'type' : 'text',
        'required' : True
    }))
    hari_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Hari',
        'type' : 'text',
        'required' : True
    }))

jadwal/views.py
from django.shortcuts import render, redirect
from . import forms, models

# Create your views here.
def jadwal(request):
    if(request.method == "POST"):
        tmp = forms.formulir(request.POST)
        if(tmp.is_valid()):
            tmp2 = models.Jadwal()
            tmp2.nama_kegiatan = tmp.cleaned_data["nama_kegiatan"]
            tmp2.hari_kegiatan = tmp.cleaned_data["hari_kegiatan"]
            tmp2.tempat_kegiatan = tmp.cleaned_data["tempat_kegiatan"]
            tmp2.kategori_kegiatan = tmp.cleaned_data["kategori_kegiatan"]
            tmp2.waktu_kegiatan = tmp.cleaned_data["waktu_kegiatan"]
            tmp2.save()
        return redirect("/jadwal")
    else:
        tmp = forms.formulir()
        tmp2 = models.Jadwal.objects.all()
        tmp_dictio = {
            'formulir' : tmp,
            'jadwal' : tmp2
        }
        return render(request, 'jadwal/jadwal.html', tmp_dictio)

def delete(request, pk):
    if(request.method == "POST"):
        tmp = forms.formulir(request.POST)
        if(tmp.is_valid()):
            tmp2 = models.Jadwal()
            tmp2.nama_kegiatan = tmp.cleaned_data["nama_kegiatan"]
            tmp2.hari_kegiatan = tmp.cleaned_data["hari_kegiatan"]
            tmp2.tempat_kegiatan = tmp.cleaned_data["tempat_kegiatan"]
            tmp2.kategori_kegiatan = tmp.cleaned_data["kategori_kegiatan"]
            tmp2.waktu_kegiatan = tmp.cleaned_data["waktu_kegiatan"]
            tmp2.save()
        return redirect("/jadwal")
    else:
        models.Jadwal.objects.filter(pk = pk).delete()
        tmp = forms.formulir()
        tmp2 = models.Jadwal.objects.all()
        tmp_dictio = {
            'formulir' : tmp,
            'jadwal' : tmp2
        }
        return render(request, 'jadwal/jadwal.html', tmp_dictio)

naufal_profile/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def porto(request):
    return render(request, 'porto.html')

jadwal/templates/jadwal/jadwal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jadwal.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Italianno|Montserrat:400,700|Raleway:400,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/d5ac12ca84.js"></script>
    <title>Jadwal</title>
</head>
<body>
    <div class="jadwal">
        <div class="juduljadwal d-flex justify-content-center">
            <p>
                <b>Jadwal</b>
            </p>
        </div>
        <div class="jadwal2">
            <form action="" method="POST">
                {% csrf_token %}
                {{ formulir }}
                <div class = "centre-items" style = "margin-top: 2%">
                    <input type = "submit" class="btn btn-primary" value="masukan"> 
                </div>
            </form>
        </div>
        <div class="table-responsive" id="Table">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Nama Kegiatan</th>
                        <th scope="col">Tempat Kegiatan</th>
                        <th scope="col">Hari Kegiatan</th>
                        <th scope="col">Waktu Kegiatan</th>
                        <th scope="col">Kategori Kegiatan</th>
                        <th scope="col">Tanggal Dibuat</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                {% for i in jadwal %}
                <tbody>
                    <tr>
                        <td>{{i.nama_kegiatan}}</td>
                        <td>{{i.tempat_kegiatan}}</td>
                        <td>{{i.hari_kegiatan}}</td>
                        <td>{{i.waktu_kegiatan}}</td>
                        <td>{{i.kategori_kegiatan}}</td>
                        <td>{{i.waktu_dibuat}}</td>
                        <td>
                            <a  href = "{% url 'hapus' pk=i.pk %}">
                                <button class="btn btn-icon btn-danger">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </a>
                        </td> 
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
        <div class="home d-flex justify-content-center">
            <a href="/">
                Home
            </a>
        </div>
    </div>
</body>
</html>

naufal_profile/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Naufal Hilmi Irfandi</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Italianno|Montserrat:400,700|Raleway:400,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/d5ac12ca84.js"></script>
</head>
<body>
    <div class="home" id="Home">
        <div class="position-relative overflow-hidden text-center">
            <div class="x-auto my-5">

                <div class="header">
                    <p class="tulisan">My Personal Website</p>    
                </div>
                
                <h1 class="judul">Naufal Hilmi Irfandi</h1>

                <div class="navbar-nav">
                    <p class="tulisan"><a class="bottomnav" href="#About">About</a> / <a class="bottomnav" href="#Experience">Experiences</a> / <a class="bottomnav" href="#Portofolio">Portofolio</a> / <a class="bottomnav" href="#Contact">Contact</a> / <a class="bottomnav" href="jadwal/">Jadwal</a></p>
                </div>

            </div>

        </div>
    </div>

    

    <div class="about" id="About">
        <div class="position-relative overflow-hidden text-center">
            <div class="x-auto my-5">
                <div class="about2 d-flex flex-wrap justify-content-around">
                    <div class="photo">
                        <img src="{% static 'image/115230.jpg' %}" alt="Naufal Hilmi Irfandi">
                    </div>
                    <div class="tulisan">
                        <h1><b>About Me,</b></h1>
                        <p>Halo kenalin nama saya Naufal Hilmi Irfandi. Saya lahir di Jepara Jawa Tengah tanggal 12 April 2000. Saya berkuliah
                        di Universitas Indonesia jurusan Ilmu Komputer, saya angkatan 2018 Quanta. Saya memiliki hobi dan minat di dunia Design seperti visual design dan design product. </p>
                    </div>
                </div>
                <div class="navbar-nav">
                    <p class="tulisan"><a class="bottomnav" href="#About">About</a> / <a class="bottomnav" href="#Experience">Experiences</a> / <a class="bottomnav" href="#Portofolio">Portofolio</a> / <a class="bottomnav" href="#Contact">Contact</a> / <a class="bottomnav" href="jadwal/">Jadwal</a> / <a class="bottomnav" href="#Home">Home</a></p>
                </div>
            </div>
        </div>
    </div>



    <div class="experiences d-flex flex-column bd-highlight align-items-center" id="Experience">
        <div class="judulexp d-flex justify-content-center">
            <h1><b>My Experiences</b></h1>
        </div>
        <div class = "experiences2 d-flex flex-wrap justify-content-around">
            <div class="photo2">
                <img src="{% static 'image/BI.png' %}" alt="Bank Indonesia">
            </div>
            <div class="tulisan">
                <p class="instansi" style="margin: 0;">Bank Indonesia</p>
                <p class="penjelasan">Alhamdulillah suatu pengalaman bagi saya untuk bisa mengikuti kegiatan magang yang diadakan oleh Bank Indonesia. Di BI, saya menjadi bagian di Departemen Pengelolaan dan Kepatuhan Laporan dimana saya membantu departemen tersebut dalam pembuatan sistem yang mendukung departemen tersebut.</p>
            </div>
        </div>
        <div class = "experiences2 d-flex flex-wrap justify-content-around">
            <div class="photo2">
                <img src="{% static 'image/Fasilkom.png' %}" alt="Fasilkom UI">
            </div>
            <div class="tulisan">
                <p class="instansi" style="margin: 0;">Fasilkom Universitas Indonesia</p>
                <p class="penjelasan">Masuk ke Fakultas Ilmu Komputer UI merupakan suatu kehormatan bagi saya. Dari Fasilkom lah saya mempelajari banyak hal seputar IT mulai dari bagaimana membuat suatu program hingga bagaimana jalannya suatu komputer.</p>
            </div>
        </div>
        <div class = "experiences2 d-flex flex-wrap justify-content-around">
            <div class="photo2">
                 <img src="{% static 'image/Bem.png' %}" alt="BEM Fasilkom">
            </div>
            <div class="tulisan">
                <p class="instansi" style="margin: 0;">BEM Fasilkom UI</p>
                <p class="penjelasan">Saya bergabung di BEM Fasilkom UI dimana saya bergabung di Biro Media dimana saya membantu Departemen Olahraga dalam melakukan publikasi seperti membuat poster untuk acara Departemen Olahraga. Adapun saya membantu dalam pembuatan video Company Profile BEM Fasilkom UI 2019. </p>
            </div>
        </div>
        <div class = "experiences2 d-flex flex-wrap justify-content-around">
            <div class="photo2">
                <img src="{% static 'image/Compfest.png' %}" alt="COMPFEST">
            </div>
            <div class="tulisan">
                <p class="instansi" style="margin: 0;">COMPFEST</p> 
                <p class="penjelasan">Di COMPFEST saya bergabung di divisi Direct Marketing dimana saya melakukan kegiatan seperti menjadi MC pada acara-acara COMPFEST, mengundang segala pihak untuk ikut bergabung di acara COMPFEST ini. Disini saya berlatih Public Speaking dan juga cara berkomunikasi dengan orang lain.</p>    
            </div>
        </div>
        <div class = "experiences2 d-flex flex-wrap justify-content-around">
            <div class="photo2">
                <img src="{% static 'image/Smansa.png' %}" alt="SMA Negeri 1 Bogor">
            </div>
            <div class="tulisan">
                <p class="instansi" style="margin: 0;">SMA Negeri 1 Bogor</p>   
                <p class="penjelasan">Disini saya pertama kali merasakan bagaimana saya bergabung dalam dunia organisasi, dimana saya melatih diri saya untuk bekerja sama dengan banyak jenis orang. Disini juga saya mengasah ilmu-ilmu pendukung untuk dunia perkuliahan.</p>  
            </div>
        </div>

        <div class="position-relative overflow-hidden text-center">
            <div class="x-auto my-5">
                <div class="navbar-nav">
                    <p class="tulisan"><a class="bottomnav" href="#About">About</a> / <a class="bottomnav" href="#Experience">Experiences</a> / <a class="bottomnav" href="#Portofolio">Portofolio</a> / <a class="bottomnav" href="#Contact">Contact</a> / <a class="bottomnav" href="jadwal/">Jadwal</a> /  <a class="bottomnav" href="#Home">Home</a></p>
                </div>
            </div>
        </div>
    </div>



    <div class="portofolio d-flex flex-column bd-highlight align-items-center" id="Portofolio">
        <div class="judulporto d-flex justify-content-center">
            <h1><b>Portofolio</b></h1>
        </div>
        <div class="overflow">
            <div class="row flex-row flex-nowrap">
                <div class="photoporto" id="first">
                    <div class="card card-block">
                        <img src="{% static 'image/IG.png' %}" alt="Photo">
                    </div>
                </div>
                <div class="photoporto">
                    <div class="card card-block">
                        <img src="{% static 'image/Selamat hari or.png' %}" alt="Photo">
                    </div>
                </div>
                <div class="photoporto">
                    <div class="card card-block">
                        <img src="{% static 'image/LBM-01.png' %}" alt="Photo">
                    </div>
                </div>
                <div class="photoporto">
                    <div class="card card-block">
                        <img src="{% static 'image/EBL.png' %}" alt="Photo">
                    </div>
                </div>
                <div class="photoporto">
                    <div class="card card-block">
                        <img src="{% static 'image/Kanan.png' %}" alt="Photo">
                    </div>
                </div>
                <div class="photoporto last">
                    <div class="card card-block">
                        <a class="photoporto2" href="{% url 'naufal_profile:porto' %}" target="_blank"><img src="{% static 'image/IG-2.png' %}" alt="Photo"></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="position-relative overflow-hidden text-center">
            <div class="x-auto my-5">
                <div class="navbar-nav">
                    <p class="tulisan"><a class="bottomnav" href="#About">About</a> / <a class="bottomnav" href="#Experience">Experiences</a> / <a class="bottomnav" href="#Portofolio">Portofolio</a> / <a class="bottomnav" href="#Contact">Contact</a> / <a class="bottomnav" href="jadwal/">Jadwal</a> / <a class="bottomnav" href="#Home">Home</a></p>
                </div>
            </div>
        </div>
    </div>



    <div class="contact" id="Contact">
        <div class="position-relative overflow-hidden text-center">
            <div class="judulcontact d-flex justify-content-center">
                <h1><b>My Contact</b></h1>
            </div>

            <div class="contact2 d-flex flex-wrap justify-content-around">
                <div class="tulisan">
                    <p>Jika membutuhkan saya, dapat melalui kontak saya dibawah ini</p>
                    <ul class="d-flex justify-content-center">
                        <li><a href= "https://twitter.com/naufalirfandi" target = "_blank"><i class="fab fa-twitter"></i></a></li>
                        <li><a href= "https://linkedin.com/in/naufal-hilmi-irfandi-25aaa8171" target = "_blank"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a href= "https://www.instagram.com/naufalirfandi/" target = "_blank"><i class="fab fa-instagram"></i></a></li>
                    </ul>
                </div>
                <div class="photo">
                    <img src="{% static 'image/115232.jpg' %}" alt="Naufal Hilmi Irfandi">
                </div>
            </div>

            <div class="x-auto my-5">
                <div class="navbar-nav">
                    <p class="tulisan"><a class="bottomnav" href="#About">About</a> / <a class="bottomnav" href="#Experience">Experiences</a> / <a class="bottomnav" href="#Portofolio">Portofolio</a> / <a class="bottomnav" href="#Contact">Contact</a> / <a class="bottomnav" href="jadwal/">Jadwal</a> / <a class="bottomnav" href="#Home">Home</a></p>
                </div>
            </div>
        </div>
    </div>


    <script src="bootstrap-4.3.1-dist\js\jquery.min.js"></script>
    <script src="bootstrap-4.3.1-dist\js\popper.min.js"></script>
    <script src="bootstrap-4.3.1-dist\js\bootstrap.min.js"></script>
</body>
</html>

naufal_profile/templates/porto.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Portofolio Naufal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Italianno|Montserrat:400,700|Raleway:400,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/d5ac12ca84.js"></script>
</head>
<body>
    <div class="porto d-flex flex-column bd-highlight align-items-center">
        <div class="judulporto d-flex justify-content-center">
            <h1><b>Portofolio</b></h1>
        </div>
        <div class="porto2 d-flex flex-wrap justify-content-center">
            <div class="photoporto">
                <img src="{% static 'image/Kanan.png' %}" alt="Portofolio">
            </div>
            <div class="photoporto">
                <img src="{% static 'image/Selamat hari or.png' %}" alt="Portofolio">
            </div>
            <div class="photoporto">
                <img src="{% static 'image/Quanta.png' %}" alt="Portofolio">
            </div>
            <div class="photoporto">
                <img src="{% static 'image/Sport Fun Fact-01.png' %}" alt="Portofolio">
            </div>
            <div class="photoporto last">
                <img src="{% static 'image/Jadwal CSTTC-01.png' %}" alt="Portofolio">
            </div>
        </div>
        <div class="porto3 d-flex flex-wrap justify-content-center">
            <div class="photoporto">
                <img src="{% static 'image/IG.png' %}" alt="Portofolio">
            </div>
            <div class="photoporto">
                <img src="{% static 'image/IG (2).png' %}" alt="Portofolio">
            </div>
            <div class="photoporto">
                <img src="{% static 'image/LBM-01.png' %}" alt="Portofolio">
            </div>
            <div class="photoporto">
                <img src="{% static 'image/EBL.png' %}" alt="Portofolio">
            </div>
            <div class="photoporto last">
                <img src="{% static 'image/Sport Fun Fact2-01.png' %}" alt="Portofolio">
            </div>
        </div>
    </div>
</body>
</html>